### ISSUE TITLE
[ask for help] how to use mqtt simulator

### ISSUE THREAD

**Issue by carolove** [cnrancher/octopus-simulator#1]
hi, i apply the mqtt simulator, but how to create a devicelink to use the simulator?
could you give a readme for help please, thank  you very much.

**Comment by thxCode** [comment]
@carolove , we will synchronize the usage of the simulator to the [Octopus](github.com/cnrancher/octopus) repo ASAP, and I will ping you later.

**Comment by thxCode** [comment]
@carolove , the simulator is in, you can follow the [example](https://cnrancher.github.io/docs-octopus/docs/en/adaptors/mqtt#example) under [deploy/e2e](https://github.com/cnrancher/octopus/tree/master/adaptors/mqtt/deploy/e2e) to have a try. 

You can reopen this issue if needed, thanks.

**Comment by carolove** [comment]
thank you for reply.
